In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
# numpy で CSV ファ イ ル を 読 み 込 む
# np.loadtxt( ファ イ ル 名 ， 句 切 り 記 号 ， 利 用 列 ) を 利 用
# torch テ ン ソ ル に 変 換 torch.Tensor()
filename = "vending_machine.csv"
x = np.loadtxt(filename, delimiter=",", skiprows=1, usecols=(0,1,2,3))
t = np.loadtxt(filename, delimiter=",", skiprows=1, usecols=(4))
x = torch.FloatTensor(x)
t = torch.FloatTensor(t).view(-1,1)

### データの形状の確認
* x: (バッチサイズ, 4)
* t: (バッチサイズ, 1)

In [3]:
x.shape, t.shape

(torch.Size([54, 4]), torch.Size([54, 1]))

In [4]:
# ネットワークの定義
class DNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(4,1)    # ここに利用するネットワーク層を書く

    # forward部分が実際の流れ。この例だと、全結合層一つだけ
    def forward(self, x):
        y = self.fc(x)
        return y

# モデルの作成
model = DNN()


In [6]:
criterion = nn.MSELoss()                                 # 損失関数を記述
#optimizer = torch.optim.SGD(model.parameters(), lr=0.001) # Adam，AdamWとかたくさんある
optimizer = torch.optim.Adam(model.parameters(), lr=0.05)

In [11]:
LOOP = 5000                               # LOOP : 学習回数
for epoch in range(LOOP):
    optimizer.zero_grad()                # 勾配初期化pytorchの約束事項
    y = model(x)                         # ネットワークモデルによる予測
    loss = criterion(y, t)               # 誤差計算pytorchの約束事項
    print(epoch,"\tloss:", loss.item())  # lossの値 (loss.item()) を表示
    loss.backward()                      # backward(微分する部分)
    optimizer.step()                     # パラメータ更新pytorchの約束事項

0 	loss: 413.8589172363281
1 	loss: 413.84906005859375
2 	loss: 413.83892822265625
3 	loss: 413.8288879394531
4 	loss: 413.8188781738281
5 	loss: 413.8089294433594
6 	loss: 413.7988586425781
7 	loss: 413.7886962890625
8 	loss: 413.7786560058594
9 	loss: 413.7688293457031
10 	loss: 413.75897216796875
11 	loss: 413.7490234375
12 	loss: 413.7389221191406
13 	loss: 413.72906494140625
14 	loss: 413.7194519042969
15 	loss: 413.7093200683594
16 	loss: 413.6995849609375
17 	loss: 413.68988037109375
18 	loss: 413.6800842285156
19 	loss: 413.67010498046875
20 	loss: 413.6604309082031
21 	loss: 413.6507568359375
22 	loss: 413.64117431640625
23 	loss: 413.631591796875
24 	loss: 413.62152099609375
25 	loss: 413.61187744140625
26 	loss: 413.6023864746094
27 	loss: 413.59283447265625
28 	loss: 413.5832214355469
29 	loss: 413.57379150390625
30 	loss: 413.5640563964844
31 	loss: 413.5545349121094
32 	loss: 413.5448913574219
33 	loss: 413.5355529785156
34 	loss: 413.5260925292969
35 	loss: 413.516632080

In [13]:
model.fc.weight, model.fc.bias

(Parameter containing:
 tensor([[ 1.6786e-01,  1.5302e+01,  1.9984e+02, -4.8021e+01]],
        requires_grad=True),
 Parameter containing:
 tensor([-7.5517], requires_grad=True))

In [17]:
x_test = [10, 25, 0.9, 0]
x_test = torch.FloatTensor(x_test)
model(x_test)

tensor([556.5385], grad_fn=<ViewBackward0>)