# PyTorchでニューラルネットワーク基礎 #01 【回帰分析】

* Qiitaの記事と連動しています
* データファイル: vending_machine.csv
* vending_macnine.csvを使った回帰分析のサンプルファイル

In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
# numpy で CSV ファ イ ル を 読 み 込 む
# np.loadtxt( ファ イ ル 名 ， 句 切 り 記 号 ， 利 用 列 ) を 利 用
# torch テ ン ソ ル に 変 換 torch.Tensor()
filename = "vending_machine.csv"
x = np.loadtxt(filename, delimiter=",", skiprows=1, usecols=(0,1,2,3))
t = np.loadtxt(filename, delimiter=",", skiprows=1, usecols=(4))
x = torch.FloatTensor(x)
t = torch.FloatTensor(t).view(-1,1)

### データの形状の確認
* x: (バッチサイズ, 4)
* t: (バッチサイズ, 1)

In [3]:
x.shape, t.shape

(torch.Size([54, 4]), torch.Size([54, 1]))

In [4]:
# ネットワークの定義
class DNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(4,1)    # ここに利用するネットワーク層を書く

    # forward部分が実際の流れ。この例だと、全結合層一つだけ
    def forward(self, x):
        y = self.fc(x)
        return y

# モデルの作成
model = DNN()


In [5]:
criterion = nn.MSELoss()                                 # 損失関数を記述
#optimizer = torch.optim.SGD(model.parameters(), lr=0.001) # Adam，AdamWとかたくさんある
optimizer = torch.optim.Adam(model.parameters(), lr=0.05)

In [6]:
LOOP = 5000                               # LOOP : 学習回数
for epoch in range(LOOP):
    optimizer.zero_grad()                # 勾配初期化pytorchの約束事項
    y = model(x)                         # ネットワークモデルによる予測
    loss = criterion(y, t)               # 誤差計算pytorchの約束事項
    print(epoch,"\tloss:", loss.item())  # lossの値 (loss.item()) を表示
    loss.backward()                      # backward(微分する部分)
    optimizer.step()                     # パラメータ更新pytorchの約束事項

0 	loss: 164586.078125
1 	loss: 163511.859375
2 	loss: 162441.359375
3 	loss: 161374.671875
4 	loss: 160311.796875
5 	loss: 159252.875
6 	loss: 158197.875
7 	loss: 157146.9375
8 	loss: 156100.09375
9 	loss: 155057.390625
10 	loss: 154018.875
11 	loss: 152984.625
12 	loss: 151954.65625
13 	loss: 150929.03125
14 	loss: 149907.828125
15 	loss: 148891.03125
16 	loss: 147878.734375
17 	loss: 146870.9375
18 	loss: 145867.71875
19 	loss: 144869.109375
20 	loss: 143875.09375
21 	loss: 142885.75
22 	loss: 141901.09375
23 	loss: 140921.140625
24 	loss: 139945.9375
25 	loss: 138975.5
26 	loss: 138009.84375
27 	loss: 137048.984375
28 	loss: 136092.96875
29 	loss: 135141.765625
30 	loss: 134195.421875
31 	loss: 133253.921875
32 	loss: 132317.3125
33 	loss: 131385.578125
34 	loss: 130458.7421875
35 	loss: 129536.78125
36 	loss: 128619.734375
37 	loss: 127707.5625
38 	loss: 126800.296875
39 	loss: 125897.9375
40 	loss: 125000.484375
41 	loss: 124107.9140625
42 	loss: 123220.2578125
43 	loss: 122337.4

In [7]:
model.fc.weight, model.fc.bias

(Parameter containing:
 tensor([[  2.5091,  15.7661, 100.0375, -54.6466]], requires_grad=True),
 Parameter containing:
 tensor([49.1775], requires_grad=True))

In [8]:
x_test = [10, 25, 0.9, 0]
x_test = torch.FloatTensor(x_test)
model(x_test)

tensor([558.4550], grad_fn=<ViewBackward0>)